# Generated by Django 3.1.1 on 2021-06-24 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
