# Generated by Django 3.1.1 on 2021-06-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0003_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='scale',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
