# Generated by Django 3.1.1 on 2021-06-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0004_auto_20210624_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
